//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobilyaciProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        public int customer_id { get; set; }
        public string customer_no { get; set; }
        public string customer_name { get; set; }
        public string customer_gsm { get; set; }
        public string customer_gsm2 { get; set; }
        public string customer_email { get; set; }
        public string customer_address { get; set; }
        public string customer_sector { get; set; }
        public string customer_iban { get; set; }
        public string customer_agent { get; set; }
        public Nullable<System.DateTime> customer_add_date { get; set; }
        public Nullable<bool> customer_status { get; set; }
    }
}
