//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobilyaciProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_attendance
    {
        public int att_id { get; set; }
        public Nullable<int> per_id { get; set; }
        public Nullable<System.DateTime> att_date { get; set; }
        public string att_type { get; set; }
    }
}
