//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobilyaciProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sale
    {
        public int slip_id { get; set; }
        public string slip_no { get; set; }
        public string customer_no { get; set; }
        public string stock_no { get; set; }
        public Nullable<long> quantity { get; set; }
        public Nullable<System.DateTime> sold_date { get; set; }
        public Nullable<long> gross_price { get; set; }
        public Nullable<long> profit { get; set; }
    }
}
