//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobilyaciProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_stock
    {
        public long stock_id { get; set; }
        public string stock_no { get; set; }
        public string stock_name { get; set; }
        public string stock_barkod { get; set; }
        public Nullable<long> stock_amount { get; set; }
        public Nullable<long> stock_price { get; set; }
        public string stock_denomination { get; set; }
        public string stock_description { get; set; }
        public Nullable<System.DateTime> stock_add_date { get; set; }
        public Nullable<bool> stock_status { get; set; }
    }
}
