//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobilyaciProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_personnel
    {
        public int per_id { get; set; }
        public string per_tc_no { get; set; }
        public string per_name { get; set; }
        public string per_surname { get; set; }
        public Nullable<System.DateTime> per_bday { get; set; }
        public string blood_type { get; set; }
        public string gender { get; set; }
        public string per_type { get; set; }
        public string marital_status { get; set; }
        public string per_gsm { get; set; }
        public string per_address { get; set; }
        public string per_mail { get; set; }
        public string per_iban { get; set; }
        public Nullable<System.DateTime> per_add_date { get; set; }
        public string per_f_no { get; set; }
        public string per_ssk_no { get; set; }
        public string per_tax_id { get; set; }
        public string per_charge { get; set; }
        public string dep_id { get; set; }
        public Nullable<bool> per_status { get; set; }
    }
}
