//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobilyaciProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_userlog
    {
        public int user_id { get; set; }
        public string user_islem { get; set; }
        public Nullable<System.DateTime> log_date { get; set; }
    }
}
