//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobilyaciProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
        public string user_nickname { get; set; }
        public string user_permission { get; set; }
        public string user_email { get; set; }
        public Nullable<System.DateTime> user_add_date { get; set; }
        public Nullable<bool> user_status { get; set; }
        public byte[] user_image { get; set; }
        public string user_imgFileName { get; set; }
    }
}
